-- Date Exploration
-- Find the date of the first and last order
SELECT
	MAX(ORDER_DATE) AS FIRST_ORDER_DATE,
	MIN(ORDER_DATE) AS LAST_ORDER_DATE,
	EXTRACT(
		YEAR
		FROM
			AGE (MAX(ORDER_DATE), MIN(ORDER_DATE))
	) AS ORDER_RANGE_YEARS
FROM
	FACT_SALES;

-- Find the youngest and the oldest customer
SELECT
	MIN(BIRTHDATE) AS OLDEST_BIRTHDATE,
	EXTRACT(
		YEAR
		FROM
			AGE (MIN(BIRTHDATE))
	) AS OLDEST_AGE,
	MAX(BIRTHDATE) AS YOUNGEST_BIRTHDATE,
	DATE_PART('year', AGE (MAX(BIRTHDATE))) AS YOUNGEST_AGE
FROM
	DIM_CUSTOMERS;
