-- Cumulative Analysis
-- Calculate the total sales per year
WITH
	YEARLY_SALES AS (
		SELECT
			DATE (DATE_TRUNC('year', ORDER_DATE)) AS ORDER_YEAR,
			SUM(SALES_AMOUNT) AS YEAR_SALES,
			AVG(PRICE) AS YEARLY_AVG
		FROM
			FACT_SALES
		WHERE
			ORDER_DATE IS NOT NULL
		GROUP BY
			DATE (DATE_TRUNC('year', ORDER_DATE))
		ORDER BY
			DATE (DATE_TRUNC('year', ORDER_DATE))
	)
SELECT
	ORDER_YEAR,
	YEAR_SALES,
	SUM(YEAR_SALES) OVER (
		ORDER BY
			ORDER_YEAR
	) AS RUNNING_YEARLY_SALES,
	ROUND(
		AVG(YEARLY_AVG) OVER (
			ORDER BY
				ORDER_YEAR
		),
		2
	) AS MOVING_AVERAGE_PRICE
FROM
	YEARLY_SALES
ORDER BY
	ORDER_YEAR;

-- by Month
WITH
	MONTHLY_SALES AS (
		SELECT
			DATE (DATE_TRUNC('month', ORDER_DATE)) AS ORDER_MONTH,
			SUM(SALES_AMOUNT) AS MONTH_SALES,
			AVG(PRICE) AS AVG_MONTH_PRICE
		FROM
			FACT_SALES
		WHERE
			ORDER_DATE IS NOT NULL
		GROUP BY
			DATE (DATE_TRUNC('month', ORDER_DATE))
		ORDER BY
			DATE (DATE_TRUNC('month', ORDER_DATE))
	)
SELECT
	ORDER_MONTH,
	MONTH_SALES,
	SUM(MONTH_SALES) OVER (
		ORDER BY
			ORDER_MONTH
	) AS RUNNING_MONTHLY_SALES,
	ROUND(
		AVG(AVG_MONTH_PRICE) OVER (
			ORDER BY
				ORDER_MONTH
		),
		2
	) AS MOVING_AVERAGE_PRICE
FROM
	MONTHLY_SALES
ORDER BY
	ORDER_MONTH;