-- Part To Whole Analysis
-- Which Categories contribute the most to overall sales?
WITH
	SALES_OVER_CATEGORY AS (
		SELECT
			P.CATEGORY,
			SUM(S.SALES_AMOUNT) AS CATEGORY_SALES,
			(
				SELECT
					SUM(SALES_AMOUNT)
				FROM
					FACT_SALES
			) AS OVERALL_SALES
		FROM
			FACT_SALES S
			JOIN DIM_PRODUCTS P ON S.PRODUCT_KEY = P.PRODUCT_KEY
		GROUP BY
			P.CATEGORY
	)
SELECT
	*,
	ROUND(
		(CATEGORY_SALES::NUMERIC / OVERALL_SALES::NUMERIC) * 100,
		2
	) || '%' AS PERCENTAGE
FROM
	SALES_OVER_CATEGORY;

-- Which Country
WITH
	SALES_OVER_COUNTRY AS (
		SELECT
			C.COUNTRY,
			SUM(S.SALES_AMOUNT) AS COUNTRY_SALES,
			(
				SELECT
					SUM(SALES_AMOUNT)
				FROM
					FACT_SALES
			) AS OVERALL_SALES
		FROM
			FACT_SALES S
			JOIN DIM_CUSTOMERS C ON S.CUSTOMER_KEY = C.CUSTOMER_KEY
		GROUP BY
			C.COUNTRY
	)
SELECT
	*,
	ROUND(
		(COUNTRY_SALES::NUMERIC / OVERALL_SALES::NUMERIC) * 100,
		2
	) || '%' AS PERCENTAGE
FROM
	SALES_OVER_COUNTRY
ORDER BY
	ROUND(
		(COUNTRY_SALES::NUMERIC / OVERALL_SALES::NUMERIC) * 100,
		2
	) DESC;
